### ISSUE TITLE
List series

### ISSUE THREAD

**Issue by ronanrodrigo** [ronanrodrigo/Sagui#1]
# Description

The app should list all series from [TVmaze API](http://api.tvmaze.com). The list should display these series data: Name, Genres and Image.
# Tasks
- [ ] Create core framework
- [ ] Create unit tests
- [ ] Create interactor
- [ ] Create presenters
- [ ] Create api gateway
- [ ] Create custom cell
- [ ] Create view controller for tableview
- [ ] Configure root view controller
