### ISSUE TITLE
Detail series

### ISSUE THREAD

**Issue by ronanrodrigo** [ronanrodrigo/Sagui#2]
# Description

The APP should show the details of a show that was touched at a series list. In the detail view, should displays that data: name, type, language, genres, status, network, image.
# Tasks
- [ ] Create view controller
- [ ] Create the view layout
- [ ] Create interactor
- [ ] Create presenters
- [ ] Create gateway
- [ ] Create mappers for show and network
