### ISSUE TITLE
Bookmark series

### ISSUE THREAD

**Issue by ronanrodrigo** [ronanrodrigo/Sagui#3]
# Description

Should be possible to bookmark some series. This will be done through an icon at the detail of series and each cell in the list of series. The bookmarked series will be identified by filled icon, and the no bookmarked will be identified by outline icon.

All bookmarked series should be persisted at the device.
# Tasks
- [ ] Add image asset or icon font
- [ ] Add button at serie cell
- [ ] Add button at detail serie view
- [ ] Create interactor
- [ ] Create presenters
- [ ] Create gateway
